### ISSUE TITLE
Duplicate key value violates unique constraint "sessions_name__key"

### ISSUE THREAD

**Issue by 1Map** [express-rate-limit/rate-limit-postgresql#17] opened 2024-01-22 19:16 UTC
### Description

Randomly I get an error message like:

```
error: duplicate key value violates unique constraint "sessions_name__key"
    at c:\myapp\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (C:\myapp\lib\internal\process\task_queues.js:95:5)
    at async createNewSession (c:\myapp\node_modules\@acpr\rate-limit-postgresql\dist\index.mjs:53:18)
    at async PostgresStoreAggregatedIP.increment (c:\myapp\node_modules\@acpr\rate-limit-postgresql\dist\index.mjs:304:22)
    at async file:///C:/myapp/node_modules/express-rate-limit/dist/index.mjs:602:40
    at async file:///C:/myapp/node_modules/express-rate-limit/dist/index.mjs:583:5 {length: 263, name: 'error', severity: 'ERROR', code: '23505', detail: 'Key (name_)=(aggregated_store) already exists.', …}
```

My Rate Limiter is setup as:

```
import { rateLimit } from 'express-rate-limit'
import { PostgresStore } from '@acpr/rate-limit-postgresql'

const apiRateLimiter = rateLimit({
  store: new PostgresStore(
    {
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      host: process.env.DB_HOST,
      database: process.env.DB_DATABASE,
      port: parseInt(process.env.DB_PORT)
    },
    'aggregated_store'
  ),
  windowMs: 1 * 60 * 1000, // 1 minute
  limit: 600, // limit each IP/email to 600 requests per windowMs (1 minute) - 10 requests per second
  delayMs: 0, // disable delaying - user has full speed until the max limit is reached
  standardHeaders: 'draft-7', // draft-6: `RateLimit-*` headers; draft-7: combined `RateLimit` header
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers.
  keyGenerator: (req, res) => {
    if (req?.currentUser?.email) {
      return req.currentUser.email
    } else {
      return req.ip
    }
  }
})
```

### Library version

@acpr/rate-limit-postgresql: ^1.3.2
express-rate-limit: ^7.1.5

### Node version

20.11.0

### Module system

ESM

**Comment by nfriedly** [comment] 2024-01-22 19:22
I believe this is specific to the postgresql store, so I'm transferring the issue over to that repo

**Comment by 1Map** [comment] 2024-01-22 19:27
> I believe this is specific to the postgresql store, so I'm transferring the issue over to that repo

Where can I find link to this?

**Comment by nfriedly** [comment] 2024-01-22 19:28
https://github.com/express-rate-limit/rate-limit-postgresql/issues/17 (it should redirect automatically from https://github.com/express-rate-limit/express-rate-limit/issues/434)

**Comment by nfriedly** [comment] 2024-01-22 19:35
@adrianprelipcean I think what's happening here is that two requests are seeing `isSessionValid()` return false at the same time and then both trying to create a new session with the same name. 

~~Maybe we want some logic in [createSession()](https://github.com/express-rate-limit/rate-limit-postgresql/blob/main/source/util/session_handler.ts#L102-L103) to handle this scenario and just look for a session that was just created?~~

Actually, I forgot that the magic is happening in a stored procedure, so maybe the check needs to be in https://github.com/express-rate-limit/rate-limit-postgresql/blob/main/source/migrations/4-add-db-functions-sessions.sql#L13-L24 ?

**Comment by nfriedly** [comment] 2024-01-22 19:49
There's some interesting things in https://stackoverflow.com/a/30770160/933879 - it sounds like `upsert`, `merge`, or `on conflict` might be helpful here.

**Comment by adrianprelipcean** [comment] 2024-01-23 05:27
Hi, I don't think that a missing UPSERT is the issue, since the function is executed within a transaction and obtains a lock on the table (which is the reason why I chose to add the logic in a stored procedure). That would mean that if you have two functions called at the same time, one would need to wait for the other's lock to be released before accessing the table. 

Is the problem occurring in a reproducible way or is it more ad hoc? If it's reproducible, can I get access to a minimum code setup that reproduces the issue? 

Thanks.

**Comment by adrianprelipcean** [comment] 2024-02-13 20:24
@nfriedly I think I identified the likely cause for this. Since the session validity is evaluated on the API server side (instead of the database), the server can receive API calls at the same time when a session is refreshed. This can result in the following two errors:
1. Create a session with the same name twice in a row (the issue reported here), which results in a `Key (name_)=(<session_name>) already exists`
2. Delete a session that is still used [in the increment operation](https://github.com/express-rate-limit/rate-limit-postgresql/blob/main/source/stores/aggregated_ip/store_aggregated_ip.ts#L108), which results in a foreign key error `error: insert or update on table "records_aggregated" violates foreign key constraint "records_aggregated_session_id_fkey"` 

I managed to reproduce it using [artillery](https://www.artillery.io/docs) with a setup of ~600 requests a second, and with a config of `windowMs: 200` and `max: 3` for the rate limiter. 

I'll look into fixing this when I get some time, the likely solution is to move the session validity evaluation on the database side instead and use it as a single source of truth.

**Closed as completed** 2024-02-27 05:30 UTC
Labels: bug
